// domain/brand.dart
enum Brand {
  americanEagle,
  chevignon,
  guess,
  columbia,
  hollister,
  uniqlo,
  bershka,
  lacoste,
  springfield,
  tommyHilfiger,
  puma,
  mango,
  forever21,
  levis,
  stradivarius,
  esprit,
  reebok,
  adidas,
  hm,
  underArmour,
  pullAndBear,
  zara,
  massimoDutti,
  nike,
  americanino,
}

extension BrandLabel on Brand {
  String get label => switch (this) {
    Brand.americanEagle => 'American Eagle',
    Brand.chevignon => 'Chevignon',
    Brand.guess => 'Guess',
    Brand.columbia => 'Columbia',
    Brand.hollister => 'Hollister',
    Brand.uniqlo => 'Uniqlo',
    Brand.bershka => 'Bershka',
    Brand.lacoste => 'Lacoste',
    Brand.springfield => 'Springfield',
    Brand.tommyHilfiger => 'Tommy Hilfiger',
    Brand.puma => 'Puma',
    Brand.mango => 'Mango',
    Brand.forever21 => 'Forever 21',
    Brand.levis => 'Levis',
    Brand.stradivarius => 'Stradivarius',
    Brand.esprit => 'Esprit',
    Brand.reebok => 'Reebok',
    Brand.adidas => 'Adidas',
    Brand.hm => 'H&M',
    Brand.underArmour => 'Under Armour',
    Brand.pullAndBear => 'Pull&Bear',
    Brand.zara => 'Zara',
    Brand.massimoDutti => 'Massimo Dutti',
    Brand.nike => 'Nike',
    Brand.americanino => 'Americanino',
  };
}
